### ISSUE TITLE
日记页面 BUG 日期标签栏重复

### ISSUE THREAD

**Issue by xdingya** [ZigZagK/typecho-theme-MDUI2333#11]
**问题回顾：**由于要将两个 Typecho 的站点合并，所以将 B 站点的文章转换成 A 站点的评论，分类到日记页面，转移完毕后日记页面卡片显示杂乱无章且日期选项卡重复
![e375aecde67a11ce2f73ac7b1f1bbae](https://xdblog-1254185734.file.myqcloud.com/usr/uploads/2022/07/800142878.png)
![2ab086097d45d5e4a6fb3d11285dbfe](https://xdblog-1254185734.file.myqcloud.com/usr/uploads/2022/07/4177009461.png)
![1561772bf17681f8f4bd95dce10791e](https://xdblog-1254185734.file.myqcloud.com/usr/uploads/2022/07/18617120.png)

大佬有解决办法吗

**Comment by ZigZagK** [comment]
主题里并没有处理这种情况的代码😭
感觉去数据库里排序，让评论恢复顺序就可以解决

**Comment by xdingya** [comment]
> 主题里并没有处理这种情况的代码😭 感觉去数据库里排序，让评论恢复顺序就可以解决

但当我该页面使用普通页的时候，这个问题就不会出现可以看看 https://xding.top/diary.html

好像普通页面也有问题，有再研究研究

**Comment by ZigZagK** [comment]
> > 主题里并没有处理这种情况的代码😭 感觉去数据库里排序，让评论恢复顺序就可以解决
> 
> 但当我该页面使用普通页的时候，这个问题就不会出现可以看看 https://xding.top/diary.html
> 
> 好像普通页面也有问题，有再研究研究

估计是typecho输出评论默认按照数据库顺序，没有按照时间排序，而日记页面调用的是typecho自带的评论输出，所以也存在这个问题。

反正应该和主题无关🤪
