### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by KawaiiZapic** [ZigZagK/typecho-theme-MDUI2333#2]
我真的超~喜欢这个主题的  
所以求求你不要鸽了无限加载评论…  
把回到顶部按钮改成标准大小而不是小的…  
以及能够优雅的自定义表情…  
还有自行存储主题配置,以免手贱换主题后又得从头配置…

**Comment by ZigZagK** [comment]
~~哇竟然有人发了IssueQAQ，超级感动~~
1.去掉无限加载评论是因为加了这个之后如果评论分页就会出现一些很难解决的事情……（比如手动输入网址跳转到评论第二页，第一页就显示不出来了）想用的话可以使用[这个版本](https://github.com/ZigZagK/typecho-theme-MDUI2333/tree/2665788599c91c13ea6fe773542aab30228b321a)，但是之后的版本估计不会用了QAQ。
2.内个……回到顶部使用小的按钮我比较喜欢，由于这个主题是私用为主的请谅解，十分抱歉QAQ，不过你可以魔改一下主题。
3.我之后的安排的确是做一个插件来方便自定义表情……但是我得学一下这种调用数据库的插件怎么写（我太菜了QAQ）……因为我现在高三了所以这个可能得等挺久的……
4.换主题之后清空配置是Typecho特性呀……每个主题都是这样的……我也很绝望QAQ……

**Comment by KawaiiZapic** [comment]
感动真的不是你咕咕咕的理由....  
1和4我理解了,感谢回复.  
2的话...能指点一下么...对MDUI不是很熟,最好具体到文件-行-内容  
3我很期待,加油!  

这个主题去掉了别的md主题一些花里胡哨的东西,还支持前端插件(这个我是最头疼的),良心.  
虽然是自用不过魔改一下就成了另一个自用了XD
另外,是学长么?高三加油哦!

**Comment by ZigZagK** [comment]
把按钮改成标准大小的话在`footer.php`第4行：
```html
<a class="mdui-fab mdui-fab-fixed mdui-fab-mini mdui-color-theme-accent mdui-ripple mdui-fab-hide" id="gototop" style="z-index:1"><i class="mdui-icon material-icons">keyboard_arrow_up</i></a>
```
把`class`里的`mdui-fab-mini`去掉就好了。
