### ISSUE TITLE
提交评论失败后无法再次提交评论

### ISSUE THREAD

**Issue by KawaiiZapic** [ZigZagK/typecho-theme-MDUI2333#3]
原因很简单:ajax提交失败后没有任何回调函数将提交按钮再次显示.  
我已经尝试修复,可以参考一下[这一次commit](https://github.com/Zapic233/typecho-theme-MDUI2333/commit/7253f4d1702886a56617ce568783a393a07f9c15#diff-e6fe04f0361d5c8758b4df146f628ed0)

**Comment by ZigZagK** [comment]
啊对……我之前发现这个问题结果忘了改，非常抱歉
将在下个版本中修正掉QAQ
