### ISSUE TITLE
Pjax不能正确处理非200响应码

### ISSUE THREAD

**Issue by KawaiiZapic** [ZigZagK/typecho-theme-MDUI2333#7]
字面意思.  
如果一篇文章是加密的,而用户未登陆,服务器会返回403错误码,并要求用户输入密码.  
但是由于错误的错误处理机制,用户只能看到加载失败的提示.  
  
建议在出错时刷新页面,可以省去很多麻烦.

**Comment by ZigZagK** [comment]
文章加密的问题应该在1.4.6里解决了，可以升级后尝试一下

**Comment by ZigZagK** [comment]
> 字面意思.
> 如果一篇文章是加密的,而用户未登陆,服务器会返回403错误码,并要求用户输入密码.
> 但是由于错误的错误处理机制,用户只能看到加载失败的提示.
> 
> 建议在出错时刷新页面,可以省去很多麻烦.

文章加密的问题应该在1.4.6里解决了，可以升级后尝试一下
