### ISSUE TITLE
使用php7.4报错

### ISSUE THREAD

**Issue by s1g0day** [ZigZagK/typecho-theme-MDUI2333#8]
非常喜欢这个主题，分类方面是我一直在寻找的折叠型分类，加上主题样式异常美观，甚是喜爱。
但在使用的过程中也发现一些小的问题，还希望您能花费一些时间阅读参考。

MDUI2333Wiki 推荐环境 PHP 7+
但我使用php7.4环境后会报错
错误信息如下：
`
Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/blog/usr/themes/MDUI2333/functions.php on line 305 
`
查其原因可能是因为    PHP7.4 不再能够使用花括号来访问数组或者字符串的偏移
我参考的文档https://www.yuanmaluntan.com/post/171.html
随后我更换了php7.3后错误便消失了，在搜索解决方法过程中发现这个问题去年曾经也有人在您的留言板提问过

随后在php7.3的环境下使用links插件时会存在警告
`
PHP报错 count(): Parameter must be an array or an object that implements Countable
`
查其原因可能是因为    7.2之后的版本 count传入非数组的变量会出现warning
我参考的文档https://blog.csdn.net/qq_33636325/article/details/89285626
虽然是插件的问题，我还是将php下调为7.1

现在问题已经解决了，但还是想提一个小小建议：
因为对php不够了解，我暂时无法确定7.x-7.3哪个版本是该主题最恰当的，也许这些问题可能在后续的版本升级时给用户带来一定的困扰
因此希望能把推荐环境 php7+ 改为确定的版本，或者是改为您开发时使用的php环境，从而避免使用者花费过多的时间去解决php的问题

再次感谢大佬提供如此优秀的主题！

**Comment by ZigZagK** [comment]
抱歉浪费了你的时间，这是由于我对PHP不够了解产生的问题QAQ。
不过我这里使用PHP7.4没有产生错误，因此没有注意到。
我目前还是网站开发小白，许多兼容性问题不够注意，也不太会规避，因此我也不太清楚什么PHP版本是最兼容的😭。
该主题的开发已经进入停滞，由于该主题应该不会被广泛使用，所以这种细节的地方可能会被我🕊了2333。
最后感谢对主题的支持！

**Comment by s1g0day** [comment]
那我也🕊了！！哈哈哈哈哈！
