### ISSUE TITLE
顶栏开往图标更改为 地铁

### ISSUE THREAD

**Issue by xdingya** [ZigZagK/typecho-theme-MDUI2333#9]
纸飞机容易造成误导可以看开往的[README.md](https://github.com/volfclub/travellings)
directions_subway（&#xe533;）

**Comment by xdingya** [comment]
而且纸飞机会审核不通过QAQ

**Comment by ZigZagK** [comment]
> 而且纸飞机会审核不通过QAQ

其实我自己这边已经更新了😂，打算在1.4.8集中更新一下某些问题。

不过这个项目其实我已经不太维护了，所以可能不知道会咕到啥时候= =。

**Comment by xdingya** [comment]
> > 表示，包括
> 
> 其实我自己这边已经更新了😂，打算在1.4.8集中更新一下某些问题。
> 
> 不过这个项目其实我已经不太维护了，所以可能不知道会咕到啥时候= =。

没关系，大佬慢慢来(您的模板已经被我二改了许多东西🌝)
